# Generated by Django 5.2.3 on 2025-07-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name="Qisqacha ma'lumot")),
                ('pdf_file', models.FileField(upload_to='resources_pdfs/', verbose_name='PDF fayl')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
