# Generated by Django 5.2.3 on 2025-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_pdfresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepublicStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('total_population', models.BigIntegerField()),
                ('age_min', models.PositiveIntegerField()),
                ('age_max', models.PositiveIntegerField()),
                ('age_population', models.BigIntegerField()),
            ],
            options={
                'unique_together': {('year', 'age_min', 'age_max')},
            },
        ),
    ]
